site:
  title: Documentation
  url: https://cyberatz.github.io/docs
  start_page: docs::index.adoc

content:
  sources:
  - url: .
    branches: [main]
    start_path: .

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
    - path: supplemental-ui/partials/footer-content.hbs
    - path: .nojekyll
    - path: css/custom.css
    - path: ui.yml
      contents: |
        static_files:
        - .nojekyll
        - css/custom.css
        styles:
        - css/custom.css

asciidoc:
  attributes:
    source-highlighter: highlight.js
    sectanchors: ''
    sectlinks: ''
    linkattrs: ''
    icons: font
    experimental: ''

output:
  dir: ./build/site

