name: Build and Deploy Antora Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'

    - name: Install Antora
      run: npm install -g @antora/cli@3.1 @antora/site-generator@3.1

    - name: Generate Antora Site
      run: antora --fetch antora-playbook.yml

    - name: Ensure docs directory exists
      run: mkdir -p docs

    - name: Generate Build Info
      run: |
        echo ":build-commit: $(git rev-parse --short HEAD)" > docs/build-info.adoc
        echo ":build-date: $(date -u +"%Y-%m-%d %H:%M UTC")" >> docs/build-info.adoc
        echo "" >> docs/build-info.adoc
        echo "Build commit: {build-commit}  " >> docs/build-info.adoc
        echo "Build date: {build-date}" >> docs/build-info.adoc

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/site

    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      if: github.ref == 'refs/heads/main'
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APP_DEPLOYMENT_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "./build/site"
        skip_app_build: true

